/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    screens: {
      "2xs": "375px",
      xs: "415px",
      s: "650px",
      ms: "768px",
      m: "900px",
      l: "1024px",
      xl: "1200px",
      xxl: "1920px",
      landscape: { orientation: "landscape" },
      portrait: { orientation: "portrait" },
      "has-hover": { raw: "(hover: hover) and (pointer: fine)" },
      "max-s": { max: "649px" },
      "max-m": { max: "1024px" },
    },
    colors: {
      white: "#ffffff",
      black: "#000000",
      blue: "#2F87B5",
      skyblue: "#E2ECF7",
      lightblue: "#8FC8E3",
      shadowblue: "#262D36",
      shadowbluelt: "#313944",
      red: "#FC5161",
      reddk: "#D1404D",
      lightred: "#FF9FA8",
      yellow: "#ECDD7B",
      yellowdk: "#A08B2D",
      green: "#779D48",
      greendk: "#5E6F49",
      tan: "#E3D4C4",
      jaffa: "#FEF6F0",
      jaffalt: "#E3D4C4",
      jaffaltfade: "rgba(227, 212, 196, 0.3)",
      jaffadk: "#BA9F82",
      grayline: "rgba(0,0,0,.07)",
      whiteline: "rgba(255,255,255,.07)",
      darkline: "#3A424D",
      transparent: "transparent",
    },
    fontFamily: {
      barlow: ["barlowmedium", "sans-serif"],
      "barlow-cond": ["barlow_condensedbold", "sans-serif"],
      "barlow-cond-semibold": ["barlow_condensedsemibold", "sans-serif"],
      helv: ["Helvetica Neue LT Pro", "sans-serif"],
      helvb: ["Helvetica Neue LT Pro Bold", "sans-serif"],
      helvh: ["Helvetica Neue LT Pro Heavy", "sans-serif"],
    },
    fontSize: {
      eyebrow: "1.7rem",
      "eyebrow-mob": "1.6rem",
      "body-xsm": "1.4rem",
      "body-xsm-mob": "1.3rem",
      "body-sm": "1.7rem",
      "body-sm-mob": "1.5rem",
      body: "2.1rem",
      "body-mob": "1.8rem",
      "body-md": "2.9rem",
      "body-md-mob": "2.1rem",
      sm: "3.3rem",
      "sm-mob": "2.3rem",
      md: "4.3rem",
      "md-mob": "2.9rem",
      lg: "5.9rem",
      "lg-mob": "3.9rem",
      xl: "11.9rem",
      "xl-mob": "5.4rem",
      xxl: "23.9rem",
      "xxl-mob": "7.9rem",
      tag: "1.4rem",
      "tag-mob": "1.3rem",
      num: "2rem",
      h5: "2rem",
    },
    lineHeight: {
      sm: "1.38",
      body: "1.31",
      md: "1.33",
      "sm-md": "1.09",
      lg: ".91",
      xl: ".82",
      xxl: ".82",
      base: "1",
    },
    letterSpacing: {
      base: ".25rem",
      sm: ".1rem",
      md: ".4rem",
    },
    borderRadius: {
      sm: ".5rem",
      base: "1rem",
      "base-mob": ".7rem",
      btn: "10rem",
      diamond: "1.6rem",
      full: "50%",
      none: "0",
    },
    zIndex: {
      ...new Array(21)
        .fill()
        .map((_, i) => i)
        .reduce((acc, val) => {
          acc[val] = val;
          return acc;
        }, {}),
    },

    extend: {
      boxShadow: {
        inner: "inset 0 0 20px rgba(0, 0, 0, 0.15)",
        submenu: ".5rem .5rem 5rem rgba(0, 0, 0, 0.20)",
        nav: ".5rem .5rem 5rem rgba(0, 0, 0, 0.1)",
        media: ".7rem .7rem 1.8rem rgba(0, 0, 0, 0.25)",
      },
      maxWidth: {
        base: "148rem",
        content: "172rem",
      },
      padding: {
        sm: ".8rem",
        "section-top": "10rem",
        "section-top-mob": "6rem",
        "section-top-lg": "15rem",
        "section-bot": "10rem",
        "section-bot-mob": "7rem",
        "section-bot-lg": "14rem",
        "hero-top": "16rem",
        "hero-top-mob": "8.5rem",
        "hero-mob-lg": "11rem",
        "post-top": "18rem",
        side: "4rem",
        "side-lg": "16rem",
        "side-mob": "2rem",
        thumb: "6.8rem",
      },
      margin: {
        sm: "1.875rem",
        side: "4rem",
        "side-mob": "2rem",
        btn: "5rem",
        md: "7rem",
      },
      borderWidth: {
        1: "1px",
        15: "1.5px",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.19, 1, 0.22, 1)",
        "out-quad": "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        "out-quint": "cubic-bezier(0.23, 1, 0.32, 1)",
      },
      space: {
        nav: "4rem",
        btn: "3rem",
        "btn-mob": "2.5rem",
        header: "3.5rem",
        "header-lg": "4rem",
        "header-mob": "2rem",
      },
      blur: {
        glow: "50px",
        big: "100px",
      },
    },
  },
};
